In [21]:
import numpy as np

In [22]:
X = np.array([[1,0,1,0], [1,0,1,1], [0,1,0,1]])
y = np.array([[1],[1],[0]])

In [23]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [24]:
y

array([[1],
       [1],
       [0]])

In [25]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [26]:
def derivativeSigmoid(x):
    return x * (1 - x)

In [38]:
inputLayer = X.shape[1]
hiddenLayer = 3
outputLayer = 1

In [39]:
epochs = 50000
alpha = 0.01

In [40]:
wh = np.random.uniform(size=(inputLayer, hiddenLayer))
bh = np.random.uniform(size=(1, hiddenLayer))
wout = np.random.uniform(size=(hiddenLayer, outputLayer))
bout = np.random.uniform(size=(1, outputLayer))

In [41]:
for i in range(epochs):
    # feedforward
    f_x = np.dot(X, wh) + bh
    z1 = sigmoid(f_x)
    f1_x = np.dot(z1, wout) + bout
    output = sigmoid(f1_x)
    
    # backpropagation
    errorOutputLayer = y - output
    slopeOutputLayer = derivativeSigmoid(output)
    deltaOutputLayer = errorOutputLayer * slopeOutputLayer
    
    errorHiddenLayer = deltaOutputLayer.dot(wout.T)
    slopeHiddenLayer = derivativeSigmoid(z1)
    deltaHiddenLayer = errorHiddenLayer * slopeHiddenLayer
    
    wout += z1.T.dot(deltaOutputLayer) * alpha
    bout += np.sum(deltaOutputLayer) * alpha
    wh += X.T.dot(deltaHiddenLayer) * alpha
    bh += np.sum(deltaHiddenLayer) * alpha

In [42]:
output

array([[0.97969127],
       [0.97106787],
       [0.0381032 ]])